<a href="https://colab.research.google.com/github/jcandane/Lie_Algebras/blob/main/sparse_lie_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Sparse-Tensor fundamental-representation of $\mathfrak{su}(N)$

###In this work, we generate the sparse $\mathfrak{su}(N)$ Lie-Algebra-elements for arbtirary $N$ in the fundamental-representation, $t^a_{\alpha\beta}$, with $a$ enumerating the elements, and $\alpha\beta$ give the spinor-basis. With-or-without the Jordan-Wigner transformation, *e.g.* $S^\pm = \frac{\sigma_x \pm i\sigma_y}{2}$. The elements are placed in the usual order (of Pauli, for $N=2$, and Gellman, for $N=3$, such that the smaller $\mathfrak{su}(N)$ sub-algebras are transparent, *i.e.* the off-diagonal-elements are followed by their Cartan-element.

j.candanedo 4/11/2023

In [1]:
import numpy as np

## regular rep (incomplete for Cartan generator constant)

In [2]:
N = 8

### reg.
sparse_elements = int( 2*N*(N-1) + N*(N+1)/2 - 1 )
i = 0 ## sparse-array entry
j = 0 ## generator-number
t = np.zeros((sparse_elements,3), dtype=np.int32)
T = np.zeros(sparse_elements, dtype=complex)
for n in range(N-1): ## loop over Cartan-generators
    for m in range(n+1): ## loop over off-diagonals
        ## real generator
        t[i] = np.array([j, m, n+1])
        T[i] = 1.
        i+=1
        t[i] = np.array([j, n+1, m])
        T[i] = 1.
        i+=1
        j+=1

        ## imag generator
        t[i] = np.array([j, m, n+1]) 
        T[i] = 1.j
        i+=1
        t[i] = np.array([j, n+1, m])
        T[i] = -1.j
        i+=1
        j+=1

    ## constant for Cartan-genorators.
    for m in range(n+1): ## loop over sparse Cartan-generator elements
        ## place-in Cartan-elements
        t[i] = np.array([j, m, m])
        T[i] = 1
        i+=1
    ## last element of Cartan generator
    t[i] = np.array([j, n+1, n+1])
    T[i] = -n-1
    i+=1
    j+=1

## Jordan-Wigner

In [3]:
N = 4000

### Jordan-Wigner Rep.
sparse_elements = int( N*(N-1) + N*(N+1)/2 - 1 )
i = 0 ## sparse-array entry
j = 0 ## generator-number
t = np.zeros((sparse_elements,3), dtype=np.int32)
T = np.zeros(sparse_elements)
for n in range(N-1): ## loop over Cartan-generators
    for m in range(n+1): ## loop over off-diagonals
        ## S^+
        t[i] = np.array([j, m, n+1])
        T[i] = 1.
        i+=1
        j+=1

        ## S^-
        t[i] = np.array([j, n+1, m]) 
        T[i] = 1.
        i+=1
        j+=1

    ## build Cartan-genorators.
    C = 1/np.sqrt( (n+1)*(n+2)/2 ) ## constant for Cartan-genorators.
    for m in range(n+1): ## loop over sparse Cartan-generator elements
        ## place-in Cartan-elements
        t[i] = np.array([j, m, m])
        T[i] = C
        i+=1
    ## last element of Cartan generator
    t[i] = np.array([j, n+1, n+1])
    T[i] = (-n-1)*C
    i+=1
    j+=1

len(t)

23997999

## result

In [4]:
def su(N, JW=False):
    """
    j.candanedo 4/11/2023
    GIVEN:  N , dimension of Lie-Algebra
            JW, choice for Jordan-Wigner Transformation
    GET:    sparse-array (t=array-of-tuples, T=data-array, out_shape=dense-array-shape)
    """

    if JW:
        sparse_elements = int( N*(N-1) + N*(N+1)/2 - 1 )
        T = np.zeros(sparse_elements)
    else:
        sparse_elements = int( 2*N*(N-1) + N*(N+1)/2 - 1 )
        T = np.zeros(sparse_elements, dtype=complex)
    i = 0 ## sparse-array entry
    j = 0 ## generator-number
    t = np.zeros((sparse_elements,3), dtype=np.int32)
    for n in range(N-1): ## loop over Cartan-generators
        for m in range(n+1): ## loop over off-diagonals
            ## real generator
            t[i] = np.array([j, m, n+1])
            T[i] = 1.
            i+=1
            if JW:
                j+=1
            t[i] = np.array([j, n+1, m])
            T[i] = 1.
            i+=1
            j+=1

            ## imag generator
            if not JW:
                t[i] = np.array([j, m, n+1]) 
                T[i] = 1.j
                i+=1
                t[i] = np.array([j, n+1, m])
                T[i] = -1.j
                i+=1
                j+=1

        ## constant for Cartan-genorators.
        C = 1/np.sqrt( (n+1)*(n+2)/2 ) ## constant for Cartan-genorators.
        for m in range(n+1): ## loop over sparse Cartan-generator elements
            ## place-in Cartan-elements
            t[i] = np.array([j, m, m])
            T[i] = C
            i+=1
        ## last element of Cartan generator
        t[i] = np.array([j, n+1, n+1])
        T[i] = -(n+1)*C
        i+=1
        j+=1
    out_shape = np.array([j,N,N])
    return t, T, out_shape

su(2, JW=True)

(array([[0, 0, 1],
        [1, 1, 0],
        [2, 0, 0],
        [2, 1, 1]], dtype=int32),
 array([ 1.,  1.,  1., -1.]),
 array([3, 2, 2]))